name: test-and-preview.yml

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    name: "Test using Playwright"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install dependencies
        run: |
          npm install
          npx playwright install-deps
          npx playwright install

      - name: Run Playwright Tests
        continue-on-error: false
        run: |
          PLAYWRIGHT_JSON_OUTPUT_NAME=./coverage/reports/results.json npx playwright test --reporter=json
          
      - name: Report Tests to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/reports/
          files: results.json
          flags: unittests
          name: codecov-mvp-website
          fail_ci_if_error: true
          verbose: true
  preview:
    name: Deploy to Cloudflare Pages (Preview)
    needs: [test]
    uses: ./.github/workflows/deploy-to-pages.yml
    secrets: inherit
